[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = "#4ecdc4"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#302b63"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true 